### ISSUE TITLE
register/unregister cmd files are not working

### ISSUE THREAD

**Issue by parthi2929** [sagamusix/TBTray#14]
When I click on TBTray it worked, but when I run the cmd files nothing happens. I then opened and check that its almost empty. 

For eg, register.cmd in 32-bit only contains below line. 

```
TBTray register
```

Thinking that my antivirus would have removed, I Checked in a linux VM also, but same content. Kindly help.

**Comment by sagamusix** [comment]
TBTray.exe does the actual registration. You need to restart the system for it to take effect.

**Comment by parthi2929** [comment]
If so, why we have these cmd files at all? what do they serve?

**Comment by sagamusix** [comment]
They serve the purpose of not having to remember the command-line parameters by heart and not having to teach people how to open a command prompt in the same folder as TBTray.exe and typing `TBTray register` / `TBTray unregister`. Ease of use, basically.
