### ISSUE TITLE
How do I install/use this program? 

### ISSUE THREAD

**Issue by euniqe** [sagamusix/TBTray#8]
I copied all files into my Thunderbird installation folder, ran copy_binaries.cmd as administrator, but no .exe file appears or anything? The CMD window also states a lot of "the system cannot find the path specified" here is an excert: 

C:\WINDOWS\system32>mkdir bin
A subdirectory or file bin already exists.

C:\WINDOWS\system32>copy README.md bin
The system cannot find the file specified.

C:\WINDOWS\system32>copy LICENSE.txt bin
The system cannot find the file specified.

C:\WINDOWS\system32>mkdir bin\32-bit
A subdirectory or file bin\32-bit already exists.

C:\WINDOWS\system32>copy Win32\Release\dll.dll bin\32-bit\TBTray.dll
The system cannot find the path specified.

C:\WINDOWS\system32>copy Win32\Release\loader.exe bin\32-bit\TBTray.exe
The system cannot find the path specified.

C:\WINDOWS\system32>echo TBTray register  1>bin\32-bit\register.cmd

C:\WINDOWS\system32>echo TBTray unregister  1>bin\32-bit\unregister.cmd

C:\WINDOWS\system32>mkdir bin\64-bit
A subdirectory or file bin\64-bit already exists.

C:\WINDOWS\system32>copy x64\Release\dll.dll bin\64-bit\TBTray.dll
The system cannot find the path specified.

C:\WINDOWS\system32>copy x64\Release\loader.exe bin\64-bit\TBTray.exe
The system cannot find the path specified.

C:\WINDOWS\system32>echo TBTray register  1>bin\64-bit\register.cmd

C:\WINDOWS\system32>echo TBTray unregister  1>bin\64-bit\unregister.cmd

C:\WINDOWS\system32>pause
Press any key to continue . . .

What am I doing wrong?

**Comment by sagamusix** [comment]
`copy_binaries.cmd` is a script to build a release. As a user you are not supposed to clone the repository, instead you need to download the [ready-made releases](https://github.com/sagamusix/TBTray/releases). All you need to do then is run `register.cmd` for the bitness that matches your Thunderbird installation. TBTray can reside anywhere, but system32 (or anything inside the Windows folder) is a particularly bad place to put it. Please put it somewhere in your user folder instead (e.g. `%localappdata%`.

**Comment by sagamusix** [comment]
Readme has been updated with clearer installation instructions.
