### ISSUE TITLE
64-bit no run

### ISSUE THREAD

**Issue by kolin-k** [sagamusix/TBTray#9]
![изображение](https://user-images.githubusercontent.com/57936126/74221779-e7d43800-4cc3-11ea-80d1-033477dcd3ab.png)

**Comment by sagamusix** [comment]
Error code C000007B means that the binary or one of its dependencies is 
not designed to run on your system architecture. Are you maybe running a 
64-bit ARM Windows version (e.g. on a tablet) and not the 64-bit Intel 
version? Also make sure that you have the VS2017 runtime installed: 
https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by kolin-k** [comment]
Thanks, work...

**Comment by sagamusix** [comment]
It would be good if you could quickly say how you made it run (e.g. did 
you install the VS2017 runtime?) so that other people running into the 
same issue can profit from your solution as well.

**Comment by kolin-k** [comment]
Installing VS2017 helped. The program has earned.
